services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: envbooker
      POSTGRES_USER: envbooker
      POSTGRES_PASSWORD: envbooker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
