# Generated by Django 6.0.5 on 2026-05-30 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("during__isempty", False),
                    ("during__lower_inf", False),
                    ("during__upper_inf", False),
                ),
                name="reservation_during_bounded",
            ),
        ),
    ]
