# Generated by Django 6.0.5 on 2026-05-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedEmailDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
