# Generated by Django 6.0.5 on 2026-06-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
